/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChatCreate,
  ChatPublic,
  ChatUpdate,
  ChatsPublic,
  HTTPValidationError,
  MessageCreate,
  MessagePublic,
  MessagesPublic,
  ReadChatsApiV1ChatsGetParams,
  ReadMessagesApiV1ChatsIdMessagesGetParams
} from '../model';

import { customInstance } from '.././axios-custom';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type readChatsApiV1ChatsGetResponse200 = {
  data: ChatsPublic
  status: 200
}

export type readChatsApiV1ChatsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readChatsApiV1ChatsGetResponseSuccess = (readChatsApiV1ChatsGetResponse200) & {
  headers: Headers;
};
export type readChatsApiV1ChatsGetResponseError = (readChatsApiV1ChatsGetResponse422) & {
  headers: Headers;
};

export type readChatsApiV1ChatsGetResponse = (readChatsApiV1ChatsGetResponseSuccess | readChatsApiV1ChatsGetResponseError)

export const getReadChatsApiV1ChatsGetUrl = (params?: ReadChatsApiV1ChatsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/chats/?${stringifiedParams}` : `/api/v1/chats/`
}

/**
 * @summary Read Chats
 */
export const readChatsApiV1ChatsGet = async (params?: ReadChatsApiV1ChatsGetParams, options?: RequestInit): Promise<readChatsApiV1ChatsGetResponse> => {

  return customInstance<readChatsApiV1ChatsGetResponse>(getReadChatsApiV1ChatsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getReadChatsApiV1ChatsGetQueryKey = (params?: ReadChatsApiV1ChatsGetParams,) => {
    return [
    `/api/v1/chats/`, ...(params ? [params] : [])
    ] as const;
    }


export const getReadChatsApiV1ChatsGetQueryOptions = <TData = Awaited<ReturnType<typeof readChatsApiV1ChatsGet>>, TError = HTTPValidationError>(params?: ReadChatsApiV1ChatsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readChatsApiV1ChatsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadChatsApiV1ChatsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readChatsApiV1ChatsGet>>> = ({ signal }) => readChatsApiV1ChatsGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readChatsApiV1ChatsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadChatsApiV1ChatsGetQueryResult = NonNullable<Awaited<ReturnType<typeof readChatsApiV1ChatsGet>>>
export type ReadChatsApiV1ChatsGetQueryError = HTTPValidationError


export function useReadChatsApiV1ChatsGet<TData = Awaited<ReturnType<typeof readChatsApiV1ChatsGet>>, TError = HTTPValidationError>(
 params: undefined |  ReadChatsApiV1ChatsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readChatsApiV1ChatsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readChatsApiV1ChatsGet>>,
          TError,
          Awaited<ReturnType<typeof readChatsApiV1ChatsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadChatsApiV1ChatsGet<TData = Awaited<ReturnType<typeof readChatsApiV1ChatsGet>>, TError = HTTPValidationError>(
 params?: ReadChatsApiV1ChatsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readChatsApiV1ChatsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readChatsApiV1ChatsGet>>,
          TError,
          Awaited<ReturnType<typeof readChatsApiV1ChatsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadChatsApiV1ChatsGet<TData = Awaited<ReturnType<typeof readChatsApiV1ChatsGet>>, TError = HTTPValidationError>(
 params?: ReadChatsApiV1ChatsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readChatsApiV1ChatsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Chats
 */

export function useReadChatsApiV1ChatsGet<TData = Awaited<ReturnType<typeof readChatsApiV1ChatsGet>>, TError = HTTPValidationError>(
 params?: ReadChatsApiV1ChatsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readChatsApiV1ChatsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadChatsApiV1ChatsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type createChatApiV1ChatsPostResponse200 = {
  data: ChatPublic
  status: 200
}

export type createChatApiV1ChatsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createChatApiV1ChatsPostResponseSuccess = (createChatApiV1ChatsPostResponse200) & {
  headers: Headers;
};
export type createChatApiV1ChatsPostResponseError = (createChatApiV1ChatsPostResponse422) & {
  headers: Headers;
};

export type createChatApiV1ChatsPostResponse = (createChatApiV1ChatsPostResponseSuccess | createChatApiV1ChatsPostResponseError)

export const getCreateChatApiV1ChatsPostUrl = () => {




  return `/api/v1/chats/`
}

/**
 * @summary Create Chat
 */
export const createChatApiV1ChatsPost = async (chatCreate: ChatCreate, options?: RequestInit): Promise<createChatApiV1ChatsPostResponse> => {

  return customInstance<createChatApiV1ChatsPostResponse>(getCreateChatApiV1ChatsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(chatCreate)
  }
);}




export const getCreateChatApiV1ChatsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createChatApiV1ChatsPost>>, TError,{data: ChatCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createChatApiV1ChatsPost>>, TError,{data: ChatCreate}, TContext> => {

const mutationKey = ['createChatApiV1ChatsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createChatApiV1ChatsPost>>, {data: ChatCreate}> = (props) => {
          const {data} = props ?? {};

          return  createChatApiV1ChatsPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateChatApiV1ChatsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createChatApiV1ChatsPost>>>
    export type CreateChatApiV1ChatsPostMutationBody = ChatCreate
    export type CreateChatApiV1ChatsPostMutationError = HTTPValidationError

    /**
 * @summary Create Chat
 */
export const useCreateChatApiV1ChatsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createChatApiV1ChatsPost>>, TError,{data: ChatCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createChatApiV1ChatsPost>>,
        TError,
        {data: ChatCreate},
        TContext
      > => {
      return useMutation(getCreateChatApiV1ChatsPostMutationOptions(options), queryClient);
    }
    export type readChatApiV1ChatsIdGetResponse200 = {
  data: ChatPublic
  status: 200
}

export type readChatApiV1ChatsIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readChatApiV1ChatsIdGetResponseSuccess = (readChatApiV1ChatsIdGetResponse200) & {
  headers: Headers;
};
export type readChatApiV1ChatsIdGetResponseError = (readChatApiV1ChatsIdGetResponse422) & {
  headers: Headers;
};

export type readChatApiV1ChatsIdGetResponse = (readChatApiV1ChatsIdGetResponseSuccess | readChatApiV1ChatsIdGetResponseError)

export const getReadChatApiV1ChatsIdGetUrl = (id: string,) => {




  return `/api/v1/chats/${id}`
}

/**
 * @summary Read Chat
 */
export const readChatApiV1ChatsIdGet = async (id: string, options?: RequestInit): Promise<readChatApiV1ChatsIdGetResponse> => {

  return customInstance<readChatApiV1ChatsIdGetResponse>(getReadChatApiV1ChatsIdGetUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getReadChatApiV1ChatsIdGetQueryKey = (id: string,) => {
    return [
    `/api/v1/chats/${id}`
    ] as const;
    }


export const getReadChatApiV1ChatsIdGetQueryOptions = <TData = Awaited<ReturnType<typeof readChatApiV1ChatsIdGet>>, TError = HTTPValidationError>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readChatApiV1ChatsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadChatApiV1ChatsIdGetQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readChatApiV1ChatsIdGet>>> = ({ signal }) => readChatApiV1ChatsIdGet(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readChatApiV1ChatsIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadChatApiV1ChatsIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof readChatApiV1ChatsIdGet>>>
export type ReadChatApiV1ChatsIdGetQueryError = HTTPValidationError


export function useReadChatApiV1ChatsIdGet<TData = Awaited<ReturnType<typeof readChatApiV1ChatsIdGet>>, TError = HTTPValidationError>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readChatApiV1ChatsIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readChatApiV1ChatsIdGet>>,
          TError,
          Awaited<ReturnType<typeof readChatApiV1ChatsIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadChatApiV1ChatsIdGet<TData = Awaited<ReturnType<typeof readChatApiV1ChatsIdGet>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readChatApiV1ChatsIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readChatApiV1ChatsIdGet>>,
          TError,
          Awaited<ReturnType<typeof readChatApiV1ChatsIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadChatApiV1ChatsIdGet<TData = Awaited<ReturnType<typeof readChatApiV1ChatsIdGet>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readChatApiV1ChatsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Chat
 */

export function useReadChatApiV1ChatsIdGet<TData = Awaited<ReturnType<typeof readChatApiV1ChatsIdGet>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readChatApiV1ChatsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadChatApiV1ChatsIdGetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type updateChatApiV1ChatsIdPutResponse200 = {
  data: ChatPublic
  status: 200
}

export type updateChatApiV1ChatsIdPutResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateChatApiV1ChatsIdPutResponseSuccess = (updateChatApiV1ChatsIdPutResponse200) & {
  headers: Headers;
};
export type updateChatApiV1ChatsIdPutResponseError = (updateChatApiV1ChatsIdPutResponse422) & {
  headers: Headers;
};

export type updateChatApiV1ChatsIdPutResponse = (updateChatApiV1ChatsIdPutResponseSuccess | updateChatApiV1ChatsIdPutResponseError)

export const getUpdateChatApiV1ChatsIdPutUrl = (id: string,) => {




  return `/api/v1/chats/${id}`
}

/**
 * @summary Update Chat
 */
export const updateChatApiV1ChatsIdPut = async (id: string,
    chatUpdate: ChatUpdate, options?: RequestInit): Promise<updateChatApiV1ChatsIdPutResponse> => {

  return customInstance<updateChatApiV1ChatsIdPutResponse>(getUpdateChatApiV1ChatsIdPutUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(chatUpdate)
  }
);}




export const getUpdateChatApiV1ChatsIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateChatApiV1ChatsIdPut>>, TError,{id: string;data: ChatUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateChatApiV1ChatsIdPut>>, TError,{id: string;data: ChatUpdate}, TContext> => {

const mutationKey = ['updateChatApiV1ChatsIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateChatApiV1ChatsIdPut>>, {id: string;data: ChatUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  updateChatApiV1ChatsIdPut(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateChatApiV1ChatsIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateChatApiV1ChatsIdPut>>>
    export type UpdateChatApiV1ChatsIdPutMutationBody = ChatUpdate
    export type UpdateChatApiV1ChatsIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Chat
 */
export const useUpdateChatApiV1ChatsIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateChatApiV1ChatsIdPut>>, TError,{id: string;data: ChatUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateChatApiV1ChatsIdPut>>,
        TError,
        {id: string;data: ChatUpdate},
        TContext
      > => {
      return useMutation(getUpdateChatApiV1ChatsIdPutMutationOptions(options), queryClient);
    }
    export type deleteChatApiV1ChatsIdDeleteResponse200 = {
  data: unknown
  status: 200
}

export type deleteChatApiV1ChatsIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteChatApiV1ChatsIdDeleteResponseSuccess = (deleteChatApiV1ChatsIdDeleteResponse200) & {
  headers: Headers;
};
export type deleteChatApiV1ChatsIdDeleteResponseError = (deleteChatApiV1ChatsIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteChatApiV1ChatsIdDeleteResponse = (deleteChatApiV1ChatsIdDeleteResponseSuccess | deleteChatApiV1ChatsIdDeleteResponseError)

export const getDeleteChatApiV1ChatsIdDeleteUrl = (id: string,) => {




  return `/api/v1/chats/${id}`
}

/**
 * @summary Delete Chat
 */
export const deleteChatApiV1ChatsIdDelete = async (id: string, options?: RequestInit): Promise<deleteChatApiV1ChatsIdDeleteResponse> => {

  return customInstance<deleteChatApiV1ChatsIdDeleteResponse>(getDeleteChatApiV1ChatsIdDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteChatApiV1ChatsIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChatApiV1ChatsIdDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteChatApiV1ChatsIdDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteChatApiV1ChatsIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteChatApiV1ChatsIdDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteChatApiV1ChatsIdDelete(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteChatApiV1ChatsIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteChatApiV1ChatsIdDelete>>>

    export type DeleteChatApiV1ChatsIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Chat
 */
export const useDeleteChatApiV1ChatsIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChatApiV1ChatsIdDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteChatApiV1ChatsIdDelete>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteChatApiV1ChatsIdDeleteMutationOptions(options), queryClient);
    }
    export type createMessageApiV1ChatsIdPostResponse200 = {
  data: MessagePublic
  status: 200
}

export type createMessageApiV1ChatsIdPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createMessageApiV1ChatsIdPostResponseSuccess = (createMessageApiV1ChatsIdPostResponse200) & {
  headers: Headers;
};
export type createMessageApiV1ChatsIdPostResponseError = (createMessageApiV1ChatsIdPostResponse422) & {
  headers: Headers;
};

export type createMessageApiV1ChatsIdPostResponse = (createMessageApiV1ChatsIdPostResponseSuccess | createMessageApiV1ChatsIdPostResponseError)

export const getCreateMessageApiV1ChatsIdPostUrl = (id: string,) => {




  return `/api/v1/chats/${id}`
}

/**
 * @summary Create Message
 */
export const createMessageApiV1ChatsIdPost = async (id: string,
    messageCreate: MessageCreate, options?: RequestInit): Promise<createMessageApiV1ChatsIdPostResponse> => {

  return customInstance<createMessageApiV1ChatsIdPostResponse>(getCreateMessageApiV1ChatsIdPostUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(messageCreate)
  }
);}




export const getCreateMessageApiV1ChatsIdPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMessageApiV1ChatsIdPost>>, TError,{id: string;data: MessageCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createMessageApiV1ChatsIdPost>>, TError,{id: string;data: MessageCreate}, TContext> => {

const mutationKey = ['createMessageApiV1ChatsIdPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMessageApiV1ChatsIdPost>>, {id: string;data: MessageCreate}> = (props) => {
          const {id,data} = props ?? {};

          return  createMessageApiV1ChatsIdPost(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateMessageApiV1ChatsIdPostMutationResult = NonNullable<Awaited<ReturnType<typeof createMessageApiV1ChatsIdPost>>>
    export type CreateMessageApiV1ChatsIdPostMutationBody = MessageCreate
    export type CreateMessageApiV1ChatsIdPostMutationError = HTTPValidationError

    /**
 * @summary Create Message
 */
export const useCreateMessageApiV1ChatsIdPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMessageApiV1ChatsIdPost>>, TError,{id: string;data: MessageCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createMessageApiV1ChatsIdPost>>,
        TError,
        {id: string;data: MessageCreate},
        TContext
      > => {
      return useMutation(getCreateMessageApiV1ChatsIdPostMutationOptions(options), queryClient);
    }
    export type readMessagesApiV1ChatsIdMessagesGetResponse200 = {
  data: MessagesPublic
  status: 200
}

export type readMessagesApiV1ChatsIdMessagesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readMessagesApiV1ChatsIdMessagesGetResponseSuccess = (readMessagesApiV1ChatsIdMessagesGetResponse200) & {
  headers: Headers;
};
export type readMessagesApiV1ChatsIdMessagesGetResponseError = (readMessagesApiV1ChatsIdMessagesGetResponse422) & {
  headers: Headers;
};

export type readMessagesApiV1ChatsIdMessagesGetResponse = (readMessagesApiV1ChatsIdMessagesGetResponseSuccess | readMessagesApiV1ChatsIdMessagesGetResponseError)

export const getReadMessagesApiV1ChatsIdMessagesGetUrl = (id: string,
    params?: ReadMessagesApiV1ChatsIdMessagesGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/chats/${id}/messages?${stringifiedParams}` : `/api/v1/chats/${id}/messages`
}

/**
 * @summary Read Messages
 */
export const readMessagesApiV1ChatsIdMessagesGet = async (id: string,
    params?: ReadMessagesApiV1ChatsIdMessagesGetParams, options?: RequestInit): Promise<readMessagesApiV1ChatsIdMessagesGetResponse> => {

  return customInstance<readMessagesApiV1ChatsIdMessagesGetResponse>(getReadMessagesApiV1ChatsIdMessagesGetUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getReadMessagesApiV1ChatsIdMessagesGetQueryKey = (id: string,
    params?: ReadMessagesApiV1ChatsIdMessagesGetParams,) => {
    return [
    `/api/v1/chats/${id}/messages`, ...(params ? [params] : [])
    ] as const;
    }


export const getReadMessagesApiV1ChatsIdMessagesGetQueryOptions = <TData = Awaited<ReturnType<typeof readMessagesApiV1ChatsIdMessagesGet>>, TError = HTTPValidationError>(id: string,
    params?: ReadMessagesApiV1ChatsIdMessagesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readMessagesApiV1ChatsIdMessagesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadMessagesApiV1ChatsIdMessagesGetQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readMessagesApiV1ChatsIdMessagesGet>>> = ({ signal }) => readMessagesApiV1ChatsIdMessagesGet(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readMessagesApiV1ChatsIdMessagesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadMessagesApiV1ChatsIdMessagesGetQueryResult = NonNullable<Awaited<ReturnType<typeof readMessagesApiV1ChatsIdMessagesGet>>>
export type ReadMessagesApiV1ChatsIdMessagesGetQueryError = HTTPValidationError


export function useReadMessagesApiV1ChatsIdMessagesGet<TData = Awaited<ReturnType<typeof readMessagesApiV1ChatsIdMessagesGet>>, TError = HTTPValidationError>(
 id: string,
    params: undefined |  ReadMessagesApiV1ChatsIdMessagesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readMessagesApiV1ChatsIdMessagesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readMessagesApiV1ChatsIdMessagesGet>>,
          TError,
          Awaited<ReturnType<typeof readMessagesApiV1ChatsIdMessagesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadMessagesApiV1ChatsIdMessagesGet<TData = Awaited<ReturnType<typeof readMessagesApiV1ChatsIdMessagesGet>>, TError = HTTPValidationError>(
 id: string,
    params?: ReadMessagesApiV1ChatsIdMessagesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readMessagesApiV1ChatsIdMessagesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readMessagesApiV1ChatsIdMessagesGet>>,
          TError,
          Awaited<ReturnType<typeof readMessagesApiV1ChatsIdMessagesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadMessagesApiV1ChatsIdMessagesGet<TData = Awaited<ReturnType<typeof readMessagesApiV1ChatsIdMessagesGet>>, TError = HTTPValidationError>(
 id: string,
    params?: ReadMessagesApiV1ChatsIdMessagesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readMessagesApiV1ChatsIdMessagesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Messages
 */

export function useReadMessagesApiV1ChatsIdMessagesGet<TData = Awaited<ReturnType<typeof readMessagesApiV1ChatsIdMessagesGet>>, TError = HTTPValidationError>(
 id: string,
    params?: ReadMessagesApiV1ChatsIdMessagesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readMessagesApiV1ChatsIdMessagesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadMessagesApiV1ChatsIdMessagesGetQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






