services:
  frontend:
    build:
      context: ./frontend
    container_name: fuet-frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - fuet-network

  backend:
    build:
      context: ./backend
    container_name: fuet-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - fuet-network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: fuet-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - fuet-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  fuet-network:
    driver: bridge
