services:
  frontend:
    build:
      context: ./frontend
    container_name: fuet-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - fuet-network

  backend:
    build:
      context: ./backend
    container_name: fuet-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - fuet-network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: fuet-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - fuet-network

  db_admin:
    image: dpage/pgadmin4:latest
    container_name: fuet-db_admin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - fuet-network
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:

networks:
  fuet-network:
    driver: bridge
