/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DocumentCreate,
  DocumentPublic,
  DocumentUpdate,
  Documentspublic,
  HTTPValidationError,
  ReadDocumentsApiV1DocumentsGetParams
} from '../model';

import { customInstance } from '.././axios-custom';
import type { ErrorType , BodyType } from '.././axios-custom';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Read Documents
 */
export const readDocumentsApiV1DocumentsGet = (
    params?: ReadDocumentsApiV1DocumentsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Documentspublic>(
      {url: `/api/v1/documents/`, method: 'GET',
        params, signal
    },
      options);
    }




export const getReadDocumentsApiV1DocumentsGetQueryKey = (params?: ReadDocumentsApiV1DocumentsGetParams,) => {
    return [
    `/api/v1/documents/`, ...(params ? [params] : [])
    ] as const;
    }


export const getReadDocumentsApiV1DocumentsGetQueryOptions = <TData = Awaited<ReturnType<typeof readDocumentsApiV1DocumentsGet>>, TError = ErrorType<HTTPValidationError>>(params?: ReadDocumentsApiV1DocumentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readDocumentsApiV1DocumentsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadDocumentsApiV1DocumentsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readDocumentsApiV1DocumentsGet>>> = ({ signal }) => readDocumentsApiV1DocumentsGet(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readDocumentsApiV1DocumentsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadDocumentsApiV1DocumentsGetQueryResult = NonNullable<Awaited<ReturnType<typeof readDocumentsApiV1DocumentsGet>>>
export type ReadDocumentsApiV1DocumentsGetQueryError = ErrorType<HTTPValidationError>


export function useReadDocumentsApiV1DocumentsGet<TData = Awaited<ReturnType<typeof readDocumentsApiV1DocumentsGet>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ReadDocumentsApiV1DocumentsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readDocumentsApiV1DocumentsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readDocumentsApiV1DocumentsGet>>,
          TError,
          Awaited<ReturnType<typeof readDocumentsApiV1DocumentsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadDocumentsApiV1DocumentsGet<TData = Awaited<ReturnType<typeof readDocumentsApiV1DocumentsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadDocumentsApiV1DocumentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readDocumentsApiV1DocumentsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readDocumentsApiV1DocumentsGet>>,
          TError,
          Awaited<ReturnType<typeof readDocumentsApiV1DocumentsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadDocumentsApiV1DocumentsGet<TData = Awaited<ReturnType<typeof readDocumentsApiV1DocumentsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadDocumentsApiV1DocumentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readDocumentsApiV1DocumentsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Documents
 */

export function useReadDocumentsApiV1DocumentsGet<TData = Awaited<ReturnType<typeof readDocumentsApiV1DocumentsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadDocumentsApiV1DocumentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readDocumentsApiV1DocumentsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadDocumentsApiV1DocumentsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Create Document
 */
export const createDocumentApiV1DocumentsPost = (
    documentCreate: BodyType<DocumentCreate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DocumentPublic>(
      {url: `/api/v1/documents/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: documentCreate, signal
    },
      options);
    }



export const getCreateDocumentApiV1DocumentsPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDocumentApiV1DocumentsPost>>, TError,{data: BodyType<DocumentCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createDocumentApiV1DocumentsPost>>, TError,{data: BodyType<DocumentCreate>}, TContext> => {

const mutationKey = ['createDocumentApiV1DocumentsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDocumentApiV1DocumentsPost>>, {data: BodyType<DocumentCreate>}> = (props) => {
          const {data} = props ?? {};

          return  createDocumentApiV1DocumentsPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateDocumentApiV1DocumentsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createDocumentApiV1DocumentsPost>>>
    export type CreateDocumentApiV1DocumentsPostMutationBody = BodyType<DocumentCreate>
    export type CreateDocumentApiV1DocumentsPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Document
 */
export const useCreateDocumentApiV1DocumentsPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDocumentApiV1DocumentsPost>>, TError,{data: BodyType<DocumentCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDocumentApiV1DocumentsPost>>,
        TError,
        {data: BodyType<DocumentCreate>},
        TContext
      > => {
      return useMutation(getCreateDocumentApiV1DocumentsPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Read Document
 */
export const readDocumentApiV1DocumentsIdGet = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DocumentPublic>(
      {url: `/api/v1/documents/${id}`, method: 'GET', signal
    },
      options);
    }




export const getReadDocumentApiV1DocumentsIdGetQueryKey = (id: string,) => {
    return [
    `/api/v1/documents/${id}`
    ] as const;
    }


export const getReadDocumentApiV1DocumentsIdGetQueryOptions = <TData = Awaited<ReturnType<typeof readDocumentApiV1DocumentsIdGet>>, TError = ErrorType<HTTPValidationError>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readDocumentApiV1DocumentsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadDocumentApiV1DocumentsIdGetQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readDocumentApiV1DocumentsIdGet>>> = ({ signal }) => readDocumentApiV1DocumentsIdGet(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readDocumentApiV1DocumentsIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadDocumentApiV1DocumentsIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof readDocumentApiV1DocumentsIdGet>>>
export type ReadDocumentApiV1DocumentsIdGetQueryError = ErrorType<HTTPValidationError>


export function useReadDocumentApiV1DocumentsIdGet<TData = Awaited<ReturnType<typeof readDocumentApiV1DocumentsIdGet>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readDocumentApiV1DocumentsIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readDocumentApiV1DocumentsIdGet>>,
          TError,
          Awaited<ReturnType<typeof readDocumentApiV1DocumentsIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadDocumentApiV1DocumentsIdGet<TData = Awaited<ReturnType<typeof readDocumentApiV1DocumentsIdGet>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readDocumentApiV1DocumentsIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readDocumentApiV1DocumentsIdGet>>,
          TError,
          Awaited<ReturnType<typeof readDocumentApiV1DocumentsIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadDocumentApiV1DocumentsIdGet<TData = Awaited<ReturnType<typeof readDocumentApiV1DocumentsIdGet>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readDocumentApiV1DocumentsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Document
 */

export function useReadDocumentApiV1DocumentsIdGet<TData = Awaited<ReturnType<typeof readDocumentApiV1DocumentsIdGet>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readDocumentApiV1DocumentsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadDocumentApiV1DocumentsIdGetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Update Document
 */
export const updateDocumentApiV1DocumentsIdPut = (
    id: string,
    documentUpdate: BodyType<DocumentUpdate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DocumentPublic>(
      {url: `/api/v1/documents/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: documentUpdate, signal
    },
      options);
    }



export const getUpdateDocumentApiV1DocumentsIdPutMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDocumentApiV1DocumentsIdPut>>, TError,{id: string;data: BodyType<DocumentUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateDocumentApiV1DocumentsIdPut>>, TError,{id: string;data: BodyType<DocumentUpdate>}, TContext> => {

const mutationKey = ['updateDocumentApiV1DocumentsIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDocumentApiV1DocumentsIdPut>>, {id: string;data: BodyType<DocumentUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateDocumentApiV1DocumentsIdPut(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateDocumentApiV1DocumentsIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateDocumentApiV1DocumentsIdPut>>>
    export type UpdateDocumentApiV1DocumentsIdPutMutationBody = BodyType<DocumentUpdate>
    export type UpdateDocumentApiV1DocumentsIdPutMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Document
 */
export const useUpdateDocumentApiV1DocumentsIdPut = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDocumentApiV1DocumentsIdPut>>, TError,{id: string;data: BodyType<DocumentUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDocumentApiV1DocumentsIdPut>>,
        TError,
        {id: string;data: BodyType<DocumentUpdate>},
        TContext
      > => {
      return useMutation(getUpdateDocumentApiV1DocumentsIdPutMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Document
 */
export const deleteDocumentApiV1DocumentsIdDelete = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/api/v1/documents/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteDocumentApiV1DocumentsIdDeleteMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentApiV1DocumentsIdDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentApiV1DocumentsIdDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteDocumentApiV1DocumentsIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDocumentApiV1DocumentsIdDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteDocumentApiV1DocumentsIdDelete(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteDocumentApiV1DocumentsIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDocumentApiV1DocumentsIdDelete>>>

    export type DeleteDocumentApiV1DocumentsIdDeleteMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Document
 */
export const useDeleteDocumentApiV1DocumentsIdDelete = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentApiV1DocumentsIdDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDocumentApiV1DocumentsIdDelete>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteDocumentApiV1DocumentsIdDeleteMutationOptions(options), queryClient);
    }
