/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CourseCreate,
  CoursePublic,
  CourseUpdate,
  CoursesPublic,
  HTTPValidationError,
  ReadCoursesApiV1CoursesGetParams
} from '../model';

import { customInstance } from '.././axios-custom';
import type { ErrorType , BodyType } from '.././axios-custom';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Read Courses
 */
export const readCoursesApiV1CoursesGet = (
    params?: ReadCoursesApiV1CoursesGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<CoursesPublic>(
      {url: `/api/v1/courses/`, method: 'GET',
        params, signal
    },
      options);
    }




export const getReadCoursesApiV1CoursesGetQueryKey = (params?: ReadCoursesApiV1CoursesGetParams,) => {
    return [
    `/api/v1/courses/`, ...(params ? [params] : [])
    ] as const;
    }


export const getReadCoursesApiV1CoursesGetQueryOptions = <TData = Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError = ErrorType<HTTPValidationError>>(params?: ReadCoursesApiV1CoursesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadCoursesApiV1CoursesGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>> = ({ signal }) => readCoursesApiV1CoursesGet(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadCoursesApiV1CoursesGetQueryResult = NonNullable<Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>>
export type ReadCoursesApiV1CoursesGetQueryError = ErrorType<HTTPValidationError>


export function useReadCoursesApiV1CoursesGet<TData = Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ReadCoursesApiV1CoursesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>,
          TError,
          Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadCoursesApiV1CoursesGet<TData = Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadCoursesApiV1CoursesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>,
          TError,
          Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadCoursesApiV1CoursesGet<TData = Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadCoursesApiV1CoursesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Courses
 */

export function useReadCoursesApiV1CoursesGet<TData = Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadCoursesApiV1CoursesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadCoursesApiV1CoursesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Create Course
 */
export const createCourseApiV1CoursesPost = (
    courseCreate: BodyType<CourseCreate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<CoursePublic>(
      {url: `/api/v1/courses/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: courseCreate, signal
    },
      options);
    }



export const getCreateCourseApiV1CoursesPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCourseApiV1CoursesPost>>, TError,{data: BodyType<CourseCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCourseApiV1CoursesPost>>, TError,{data: BodyType<CourseCreate>}, TContext> => {

const mutationKey = ['createCourseApiV1CoursesPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCourseApiV1CoursesPost>>, {data: BodyType<CourseCreate>}> = (props) => {
          const {data} = props ?? {};

          return  createCourseApiV1CoursesPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCourseApiV1CoursesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createCourseApiV1CoursesPost>>>
    export type CreateCourseApiV1CoursesPostMutationBody = BodyType<CourseCreate>
    export type CreateCourseApiV1CoursesPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Course
 */
export const useCreateCourseApiV1CoursesPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCourseApiV1CoursesPost>>, TError,{data: BodyType<CourseCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCourseApiV1CoursesPost>>,
        TError,
        {data: BodyType<CourseCreate>},
        TContext
      > => {
      return useMutation(getCreateCourseApiV1CoursesPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Read Course
 */
export const readCourseApiV1CoursesIdGet = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<CoursePublic>(
      {url: `/api/v1/courses/${id}`, method: 'GET', signal
    },
      options);
    }




export const getReadCourseApiV1CoursesIdGetQueryKey = (id: string,) => {
    return [
    `/api/v1/courses/${id}`
    ] as const;
    }


export const getReadCourseApiV1CoursesIdGetQueryOptions = <TData = Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError = ErrorType<HTTPValidationError>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadCourseApiV1CoursesIdGetQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>> = ({ signal }) => readCourseApiV1CoursesIdGet(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadCourseApiV1CoursesIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>>
export type ReadCourseApiV1CoursesIdGetQueryError = ErrorType<HTTPValidationError>


export function useReadCourseApiV1CoursesIdGet<TData = Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>,
          TError,
          Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadCourseApiV1CoursesIdGet<TData = Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>,
          TError,
          Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadCourseApiV1CoursesIdGet<TData = Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Course
 */

export function useReadCourseApiV1CoursesIdGet<TData = Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadCourseApiV1CoursesIdGetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Update Course
 */
export const updateCourseApiV1CoursesIdPut = (
    id: string,
    courseUpdate: BodyType<CourseUpdate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<CoursePublic>(
      {url: `/api/v1/courses/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: courseUpdate, signal
    },
      options);
    }



export const getUpdateCourseApiV1CoursesIdPutMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCourseApiV1CoursesIdPut>>, TError,{id: string;data: BodyType<CourseUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCourseApiV1CoursesIdPut>>, TError,{id: string;data: BodyType<CourseUpdate>}, TContext> => {

const mutationKey = ['updateCourseApiV1CoursesIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCourseApiV1CoursesIdPut>>, {id: string;data: BodyType<CourseUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateCourseApiV1CoursesIdPut(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateCourseApiV1CoursesIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateCourseApiV1CoursesIdPut>>>
    export type UpdateCourseApiV1CoursesIdPutMutationBody = BodyType<CourseUpdate>
    export type UpdateCourseApiV1CoursesIdPutMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Course
 */
export const useUpdateCourseApiV1CoursesIdPut = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCourseApiV1CoursesIdPut>>, TError,{id: string;data: BodyType<CourseUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCourseApiV1CoursesIdPut>>,
        TError,
        {id: string;data: BodyType<CourseUpdate>},
        TContext
      > => {
      return useMutation(getUpdateCourseApiV1CoursesIdPutMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Course
 */
export const deleteCourseApiV1CoursesIdDelete = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/api/v1/courses/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteCourseApiV1CoursesIdDeleteMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCourseApiV1CoursesIdDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCourseApiV1CoursesIdDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteCourseApiV1CoursesIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCourseApiV1CoursesIdDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteCourseApiV1CoursesIdDelete(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCourseApiV1CoursesIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCourseApiV1CoursesIdDelete>>>

    export type DeleteCourseApiV1CoursesIdDeleteMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Course
 */
export const useDeleteCourseApiV1CoursesIdDelete = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCourseApiV1CoursesIdDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCourseApiV1CoursesIdDelete>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteCourseApiV1CoursesIdDeleteMutationOptions(options), queryClient);
    }
