/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CourseCreate,
  CoursePublic,
  CourseUpdate,
  CoursesPublic,
  HTTPValidationError,
  ReadCoursesApiV1CoursesGetParams
} from '../model';

import { customInstance } from '.././axios-custom';




export type readCoursesApiV1CoursesGetResponse200 = {
  data: CoursesPublic
  status: 200
}

export type readCoursesApiV1CoursesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readCoursesApiV1CoursesGetResponseSuccess = (readCoursesApiV1CoursesGetResponse200) & {
  headers: Headers;
};
export type readCoursesApiV1CoursesGetResponseError = (readCoursesApiV1CoursesGetResponse422) & {
  headers: Headers;
};

export type readCoursesApiV1CoursesGetResponse = (readCoursesApiV1CoursesGetResponseSuccess | readCoursesApiV1CoursesGetResponseError)

export const getReadCoursesApiV1CoursesGetUrl = (params?: ReadCoursesApiV1CoursesGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/courses/?${stringifiedParams}` : `/api/v1/courses/`
}

/**
 * @summary Read Courses
 */
export const readCoursesApiV1CoursesGet = async (params?: ReadCoursesApiV1CoursesGetParams, options?: RequestInit): Promise<readCoursesApiV1CoursesGetResponse> => {

  return customInstance<readCoursesApiV1CoursesGetResponse>(getReadCoursesApiV1CoursesGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getReadCoursesApiV1CoursesGetQueryKey = (params?: ReadCoursesApiV1CoursesGetParams,) => {
    return [
    `/api/v1/courses/`, ...(params ? [params] : [])
    ] as const;
    }


export const getReadCoursesApiV1CoursesGetQueryOptions = <TData = Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError = HTTPValidationError>(params?: ReadCoursesApiV1CoursesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadCoursesApiV1CoursesGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>> = ({ signal }) => readCoursesApiV1CoursesGet(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadCoursesApiV1CoursesGetQueryResult = NonNullable<Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>>
export type ReadCoursesApiV1CoursesGetQueryError = HTTPValidationError


export function useReadCoursesApiV1CoursesGet<TData = Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError = HTTPValidationError>(
 params: undefined |  ReadCoursesApiV1CoursesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>,
          TError,
          Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadCoursesApiV1CoursesGet<TData = Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError = HTTPValidationError>(
 params?: ReadCoursesApiV1CoursesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>,
          TError,
          Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadCoursesApiV1CoursesGet<TData = Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError = HTTPValidationError>(
 params?: ReadCoursesApiV1CoursesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Courses
 */

export function useReadCoursesApiV1CoursesGet<TData = Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError = HTTPValidationError>(
 params?: ReadCoursesApiV1CoursesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCoursesApiV1CoursesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadCoursesApiV1CoursesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type createCourseApiV1CoursesPostResponse200 = {
  data: CoursePublic
  status: 200
}

export type createCourseApiV1CoursesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createCourseApiV1CoursesPostResponseSuccess = (createCourseApiV1CoursesPostResponse200) & {
  headers: Headers;
};
export type createCourseApiV1CoursesPostResponseError = (createCourseApiV1CoursesPostResponse422) & {
  headers: Headers;
};

export type createCourseApiV1CoursesPostResponse = (createCourseApiV1CoursesPostResponseSuccess | createCourseApiV1CoursesPostResponseError)

export const getCreateCourseApiV1CoursesPostUrl = () => {




  return `/api/v1/courses/`
}

/**
 * @summary Create Course
 */
export const createCourseApiV1CoursesPost = async (courseCreate: CourseCreate, options?: RequestInit): Promise<createCourseApiV1CoursesPostResponse> => {

  return customInstance<createCourseApiV1CoursesPostResponse>(getCreateCourseApiV1CoursesPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(courseCreate)
  }
);}




export const getCreateCourseApiV1CoursesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCourseApiV1CoursesPost>>, TError,{data: CourseCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createCourseApiV1CoursesPost>>, TError,{data: CourseCreate}, TContext> => {

const mutationKey = ['createCourseApiV1CoursesPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCourseApiV1CoursesPost>>, {data: CourseCreate}> = (props) => {
          const {data} = props ?? {};

          return  createCourseApiV1CoursesPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCourseApiV1CoursesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createCourseApiV1CoursesPost>>>
    export type CreateCourseApiV1CoursesPostMutationBody = CourseCreate
    export type CreateCourseApiV1CoursesPostMutationError = HTTPValidationError

    /**
 * @summary Create Course
 */
export const useCreateCourseApiV1CoursesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCourseApiV1CoursesPost>>, TError,{data: CourseCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCourseApiV1CoursesPost>>,
        TError,
        {data: CourseCreate},
        TContext
      > => {
      return useMutation(getCreateCourseApiV1CoursesPostMutationOptions(options), queryClient);
    }
    export type readCourseApiV1CoursesIdGetResponse200 = {
  data: CoursePublic
  status: 200
}

export type readCourseApiV1CoursesIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readCourseApiV1CoursesIdGetResponseSuccess = (readCourseApiV1CoursesIdGetResponse200) & {
  headers: Headers;
};
export type readCourseApiV1CoursesIdGetResponseError = (readCourseApiV1CoursesIdGetResponse422) & {
  headers: Headers;
};

export type readCourseApiV1CoursesIdGetResponse = (readCourseApiV1CoursesIdGetResponseSuccess | readCourseApiV1CoursesIdGetResponseError)

export const getReadCourseApiV1CoursesIdGetUrl = (id: string,) => {




  return `/api/v1/courses/${id}`
}

/**
 * @summary Read Course
 */
export const readCourseApiV1CoursesIdGet = async (id: string, options?: RequestInit): Promise<readCourseApiV1CoursesIdGetResponse> => {

  return customInstance<readCourseApiV1CoursesIdGetResponse>(getReadCourseApiV1CoursesIdGetUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getReadCourseApiV1CoursesIdGetQueryKey = (id: string,) => {
    return [
    `/api/v1/courses/${id}`
    ] as const;
    }


export const getReadCourseApiV1CoursesIdGetQueryOptions = <TData = Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError = HTTPValidationError>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadCourseApiV1CoursesIdGetQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>> = ({ signal }) => readCourseApiV1CoursesIdGet(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadCourseApiV1CoursesIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>>
export type ReadCourseApiV1CoursesIdGetQueryError = HTTPValidationError


export function useReadCourseApiV1CoursesIdGet<TData = Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError = HTTPValidationError>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>,
          TError,
          Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadCourseApiV1CoursesIdGet<TData = Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>,
          TError,
          Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadCourseApiV1CoursesIdGet<TData = Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Course
 */

export function useReadCourseApiV1CoursesIdGet<TData = Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readCourseApiV1CoursesIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadCourseApiV1CoursesIdGetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type updateCourseApiV1CoursesIdPutResponse200 = {
  data: CoursePublic
  status: 200
}

export type updateCourseApiV1CoursesIdPutResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateCourseApiV1CoursesIdPutResponseSuccess = (updateCourseApiV1CoursesIdPutResponse200) & {
  headers: Headers;
};
export type updateCourseApiV1CoursesIdPutResponseError = (updateCourseApiV1CoursesIdPutResponse422) & {
  headers: Headers;
};

export type updateCourseApiV1CoursesIdPutResponse = (updateCourseApiV1CoursesIdPutResponseSuccess | updateCourseApiV1CoursesIdPutResponseError)

export const getUpdateCourseApiV1CoursesIdPutUrl = (id: string,) => {




  return `/api/v1/courses/${id}`
}

/**
 * @summary Update Course
 */
export const updateCourseApiV1CoursesIdPut = async (id: string,
    courseUpdate: CourseUpdate, options?: RequestInit): Promise<updateCourseApiV1CoursesIdPutResponse> => {

  return customInstance<updateCourseApiV1CoursesIdPutResponse>(getUpdateCourseApiV1CoursesIdPutUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(courseUpdate)
  }
);}




export const getUpdateCourseApiV1CoursesIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCourseApiV1CoursesIdPut>>, TError,{id: string;data: CourseUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateCourseApiV1CoursesIdPut>>, TError,{id: string;data: CourseUpdate}, TContext> => {

const mutationKey = ['updateCourseApiV1CoursesIdPut'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCourseApiV1CoursesIdPut>>, {id: string;data: CourseUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  updateCourseApiV1CoursesIdPut(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateCourseApiV1CoursesIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateCourseApiV1CoursesIdPut>>>
    export type UpdateCourseApiV1CoursesIdPutMutationBody = CourseUpdate
    export type UpdateCourseApiV1CoursesIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Course
 */
export const useUpdateCourseApiV1CoursesIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCourseApiV1CoursesIdPut>>, TError,{id: string;data: CourseUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCourseApiV1CoursesIdPut>>,
        TError,
        {id: string;data: CourseUpdate},
        TContext
      > => {
      return useMutation(getUpdateCourseApiV1CoursesIdPutMutationOptions(options), queryClient);
    }
    export type deleteCourseApiV1CoursesIdDeleteResponse200 = {
  data: unknown
  status: 200
}

export type deleteCourseApiV1CoursesIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteCourseApiV1CoursesIdDeleteResponseSuccess = (deleteCourseApiV1CoursesIdDeleteResponse200) & {
  headers: Headers;
};
export type deleteCourseApiV1CoursesIdDeleteResponseError = (deleteCourseApiV1CoursesIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteCourseApiV1CoursesIdDeleteResponse = (deleteCourseApiV1CoursesIdDeleteResponseSuccess | deleteCourseApiV1CoursesIdDeleteResponseError)

export const getDeleteCourseApiV1CoursesIdDeleteUrl = (id: string,) => {




  return `/api/v1/courses/${id}`
}

/**
 * @summary Delete Course
 */
export const deleteCourseApiV1CoursesIdDelete = async (id: string, options?: RequestInit): Promise<deleteCourseApiV1CoursesIdDeleteResponse> => {

  return customInstance<deleteCourseApiV1CoursesIdDeleteResponse>(getDeleteCourseApiV1CoursesIdDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteCourseApiV1CoursesIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCourseApiV1CoursesIdDelete>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteCourseApiV1CoursesIdDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteCourseApiV1CoursesIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCourseApiV1CoursesIdDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteCourseApiV1CoursesIdDelete(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCourseApiV1CoursesIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCourseApiV1CoursesIdDelete>>>

    export type DeleteCourseApiV1CoursesIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Course
 */
export const useDeleteCourseApiV1CoursesIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCourseApiV1CoursesIdDelete>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCourseApiV1CoursesIdDelete>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteCourseApiV1CoursesIdDeleteMutationOptions(options), queryClient);
    }
