/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError
} from '../model';

import { customInstance } from '.././axios-custom';
import type { ErrorType } from '.././axios-custom';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Download File
 */
export const downloadFileApiV1R2StorageDownloadFilepathGet = (
    filepath: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown | Blob>(
      {url: `/api/v1/r2_storage/download/${filepath}`, method: 'GET',
        responseType: 'blob', signal
    },
      options);
    }




export const getDownloadFileApiV1R2StorageDownloadFilepathGetInfiniteQueryKey = (filepath: string,) => {
    return [
    'infinite', `/api/v1/r2_storage/download/${filepath}`
    ] as const;
    }

export const getDownloadFileApiV1R2StorageDownloadFilepathGetQueryKey = (filepath: string,) => {
    return [
    `/api/v1/r2_storage/download/${filepath}`
    ] as const;
    }


export const getDownloadFileApiV1R2StorageDownloadFilepathGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>>, TError = ErrorType<HTTPValidationError>>(filepath: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadFileApiV1R2StorageDownloadFilepathGetInfiniteQueryKey(filepath);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>> = ({ signal }) => downloadFileApiV1R2StorageDownloadFilepathGet(filepath, requestOptions, signal);





   return  { queryKey, queryFn, enabled: filepath !== null && filepath !== undefined, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadFileApiV1R2StorageDownloadFilepathGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>>
export type DownloadFileApiV1R2StorageDownloadFilepathGetInfiniteQueryError = ErrorType<HTTPValidationError>


export function useDownloadFileApiV1R2StorageDownloadFilepathGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>>, TError = ErrorType<HTTPValidationError>>(
 filepath: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>,
          TError,
          Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadFileApiV1R2StorageDownloadFilepathGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>>, TError = ErrorType<HTTPValidationError>>(
 filepath: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>,
          TError,
          Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadFileApiV1R2StorageDownloadFilepathGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>>, TError = ErrorType<HTTPValidationError>>(
 filepath: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download File
 */

export function useDownloadFileApiV1R2StorageDownloadFilepathGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>>, TError = ErrorType<HTTPValidationError>>(
 filepath: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadFileApiV1R2StorageDownloadFilepathGetInfiniteQueryOptions(filepath,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getDownloadFileApiV1R2StorageDownloadFilepathGetQueryOptions = <TData = Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>, TError = ErrorType<HTTPValidationError>>(filepath: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadFileApiV1R2StorageDownloadFilepathGetQueryKey(filepath);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>> = ({ signal }) => downloadFileApiV1R2StorageDownloadFilepathGet(filepath, requestOptions, signal);





   return  { queryKey, queryFn, enabled: filepath !== null && filepath !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadFileApiV1R2StorageDownloadFilepathGetQueryResult = NonNullable<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>>
export type DownloadFileApiV1R2StorageDownloadFilepathGetQueryError = ErrorType<HTTPValidationError>


export function useDownloadFileApiV1R2StorageDownloadFilepathGet<TData = Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>, TError = ErrorType<HTTPValidationError>>(
 filepath: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>,
          TError,
          Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadFileApiV1R2StorageDownloadFilepathGet<TData = Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>, TError = ErrorType<HTTPValidationError>>(
 filepath: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>,
          TError,
          Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadFileApiV1R2StorageDownloadFilepathGet<TData = Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>, TError = ErrorType<HTTPValidationError>>(
 filepath: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download File
 */

export function useDownloadFileApiV1R2StorageDownloadFilepathGet<TData = Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>, TError = ErrorType<HTTPValidationError>>(
 filepath: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadFileApiV1R2StorageDownloadFilepathGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadFileApiV1R2StorageDownloadFilepathGetQueryOptions(filepath,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary List Files
 */
export const listFilesApiV1R2StorageListFilesPrefixGet = (
    prefix: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/api/v1/r2_storage/list-files/${prefix}`, method: 'GET', signal
    },
      options);
    }




export const getListFilesApiV1R2StorageListFilesPrefixGetInfiniteQueryKey = (prefix: string,) => {
    return [
    'infinite', `/api/v1/r2_storage/list-files/${prefix}`
    ] as const;
    }

export const getListFilesApiV1R2StorageListFilesPrefixGetQueryKey = (prefix: string,) => {
    return [
    `/api/v1/r2_storage/list-files/${prefix}`
    ] as const;
    }


export const getListFilesApiV1R2StorageListFilesPrefixGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>>, TError = ErrorType<HTTPValidationError>>(prefix: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFilesApiV1R2StorageListFilesPrefixGetInfiniteQueryKey(prefix);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>> = ({ signal }) => listFilesApiV1R2StorageListFilesPrefixGet(prefix, requestOptions, signal);





   return  { queryKey, queryFn, enabled: prefix !== null && prefix !== undefined, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFilesApiV1R2StorageListFilesPrefixGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>>
export type ListFilesApiV1R2StorageListFilesPrefixGetInfiniteQueryError = ErrorType<HTTPValidationError>


export function useListFilesApiV1R2StorageListFilesPrefixGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>>, TError = ErrorType<HTTPValidationError>>(
 prefix: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>,
          TError,
          Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFilesApiV1R2StorageListFilesPrefixGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>>, TError = ErrorType<HTTPValidationError>>(
 prefix: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>,
          TError,
          Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFilesApiV1R2StorageListFilesPrefixGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>>, TError = ErrorType<HTTPValidationError>>(
 prefix: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Files
 */

export function useListFilesApiV1R2StorageListFilesPrefixGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>>, TError = ErrorType<HTTPValidationError>>(
 prefix: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFilesApiV1R2StorageListFilesPrefixGetInfiniteQueryOptions(prefix,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getListFilesApiV1R2StorageListFilesPrefixGetQueryOptions = <TData = Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>, TError = ErrorType<HTTPValidationError>>(prefix: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFilesApiV1R2StorageListFilesPrefixGetQueryKey(prefix);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>> = ({ signal }) => listFilesApiV1R2StorageListFilesPrefixGet(prefix, requestOptions, signal);





   return  { queryKey, queryFn, enabled: prefix !== null && prefix !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFilesApiV1R2StorageListFilesPrefixGetQueryResult = NonNullable<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>>
export type ListFilesApiV1R2StorageListFilesPrefixGetQueryError = ErrorType<HTTPValidationError>


export function useListFilesApiV1R2StorageListFilesPrefixGet<TData = Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>, TError = ErrorType<HTTPValidationError>>(
 prefix: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>,
          TError,
          Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFilesApiV1R2StorageListFilesPrefixGet<TData = Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>, TError = ErrorType<HTTPValidationError>>(
 prefix: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>,
          TError,
          Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFilesApiV1R2StorageListFilesPrefixGet<TData = Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>, TError = ErrorType<HTTPValidationError>>(
 prefix: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Files
 */

export function useListFilesApiV1R2StorageListFilesPrefixGet<TData = Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>, TError = ErrorType<HTTPValidationError>>(
 prefix: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFilesApiV1R2StorageListFilesPrefixGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFilesApiV1R2StorageListFilesPrefixGetQueryOptions(prefix,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Get Bucket Usage
 */
export const getBucketUsageApiV1R2StorageUsageGet = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/api/v1/r2_storage/usage`, method: 'GET', signal
    },
      options);
    }




export const getGetBucketUsageApiV1R2StorageUsageGetInfiniteQueryKey = () => {
    return [
    'infinite', `/api/v1/r2_storage/usage`
    ] as const;
    }

export const getGetBucketUsageApiV1R2StorageUsageGetQueryKey = () => {
    return [
    `/api/v1/r2_storage/usage`
    ] as const;
    }


export const getGetBucketUsageApiV1R2StorageUsageGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBucketUsageApiV1R2StorageUsageGetInfiniteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>> = ({ signal }) => getBucketUsageApiV1R2StorageUsageGet(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBucketUsageApiV1R2StorageUsageGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>>
export type GetBucketUsageApiV1R2StorageUsageGetInfiniteQueryError = ErrorType<unknown>


export function useGetBucketUsageApiV1R2StorageUsageGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>,
          TError,
          Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBucketUsageApiV1R2StorageUsageGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>,
          TError,
          Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBucketUsageApiV1R2StorageUsageGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Bucket Usage
 */

export function useGetBucketUsageApiV1R2StorageUsageGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBucketUsageApiV1R2StorageUsageGetInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetBucketUsageApiV1R2StorageUsageGetQueryOptions = <TData = Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBucketUsageApiV1R2StorageUsageGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>> = ({ signal }) => getBucketUsageApiV1R2StorageUsageGet(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBucketUsageApiV1R2StorageUsageGetQueryResult = NonNullable<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>>
export type GetBucketUsageApiV1R2StorageUsageGetQueryError = ErrorType<unknown>


export function useGetBucketUsageApiV1R2StorageUsageGet<TData = Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>,
          TError,
          Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBucketUsageApiV1R2StorageUsageGet<TData = Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>,
          TError,
          Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBucketUsageApiV1R2StorageUsageGet<TData = Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Bucket Usage
 */

export function useGetBucketUsageApiV1R2StorageUsageGet<TData = Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBucketUsageApiV1R2StorageUsageGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBucketUsageApiV1R2StorageUsageGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Get Document File Url
 */
export const getDocumentFileUrlApiV1R2StorageFilePathUrlGet = (
    filePath: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/api/v1/r2_storage${filePath}/url`, method: 'GET', signal
    },
      options);
    }




export const getGetDocumentFileUrlApiV1R2StorageFilePathUrlGetInfiniteQueryKey = (filePath: string,) => {
    return [
    'infinite', `/api/v1/r2_storage${filePath}/url`
    ] as const;
    }

export const getGetDocumentFileUrlApiV1R2StorageFilePathUrlGetQueryKey = (filePath: string,) => {
    return [
    `/api/v1/r2_storage${filePath}/url`
    ] as const;
    }


export const getGetDocumentFileUrlApiV1R2StorageFilePathUrlGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>>, TError = ErrorType<HTTPValidationError>>(filePath: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentFileUrlApiV1R2StorageFilePathUrlGetInfiniteQueryKey(filePath);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>> = ({ signal }) => getDocumentFileUrlApiV1R2StorageFilePathUrlGet(filePath, requestOptions, signal);





   return  { queryKey, queryFn, enabled: filePath !== null && filePath !== undefined, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentFileUrlApiV1R2StorageFilePathUrlGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>>
export type GetDocumentFileUrlApiV1R2StorageFilePathUrlGetInfiniteQueryError = ErrorType<HTTPValidationError>


export function useGetDocumentFileUrlApiV1R2StorageFilePathUrlGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>>, TError = ErrorType<HTTPValidationError>>(
 filePath: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>,
          TError,
          Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentFileUrlApiV1R2StorageFilePathUrlGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>>, TError = ErrorType<HTTPValidationError>>(
 filePath: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>,
          TError,
          Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentFileUrlApiV1R2StorageFilePathUrlGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>>, TError = ErrorType<HTTPValidationError>>(
 filePath: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Document File Url
 */

export function useGetDocumentFileUrlApiV1R2StorageFilePathUrlGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>>, TError = ErrorType<HTTPValidationError>>(
 filePath: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocumentFileUrlApiV1R2StorageFilePathUrlGetInfiniteQueryOptions(filePath,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetDocumentFileUrlApiV1R2StorageFilePathUrlGetQueryOptions = <TData = Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>, TError = ErrorType<HTTPValidationError>>(filePath: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentFileUrlApiV1R2StorageFilePathUrlGetQueryKey(filePath);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>> = ({ signal }) => getDocumentFileUrlApiV1R2StorageFilePathUrlGet(filePath, requestOptions, signal);





   return  { queryKey, queryFn, enabled: filePath !== null && filePath !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentFileUrlApiV1R2StorageFilePathUrlGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>>
export type GetDocumentFileUrlApiV1R2StorageFilePathUrlGetQueryError = ErrorType<HTTPValidationError>


export function useGetDocumentFileUrlApiV1R2StorageFilePathUrlGet<TData = Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>, TError = ErrorType<HTTPValidationError>>(
 filePath: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>,
          TError,
          Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentFileUrlApiV1R2StorageFilePathUrlGet<TData = Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>, TError = ErrorType<HTTPValidationError>>(
 filePath: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>,
          TError,
          Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentFileUrlApiV1R2StorageFilePathUrlGet<TData = Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>, TError = ErrorType<HTTPValidationError>>(
 filePath: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Document File Url
 */

export function useGetDocumentFileUrlApiV1R2StorageFilePathUrlGet<TData = Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>, TError = ErrorType<HTTPValidationError>>(
 filePath: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentFileUrlApiV1R2StorageFilePathUrlGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocumentFileUrlApiV1R2StorageFilePathUrlGetQueryOptions(filePath,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






