/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ChatPublic } from './chatPublic';

export interface ChatsPublic {
  data: ChatPublic[];
  count: number;
}
