/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ChatPublic {
  /**
     * @minLength 1
     * @maxLength 255
     */
  title: string;
  id: string;
  pinned: boolean;
  created_at?: string | null;
}
