/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ChatCreate {
  /**
     * @minLength 1
     * @maxLength 255
     */
  title: string;
}
