/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface CoursePublic {
  code: string | null;
  name: string;
  course_id: string;
}
