/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentPublic } from './documentPublic';

export interface Documentspublic {
  data: DocumentPublic[];
  count: number;
  page: number;
  page_size: number;
  total_pages: number;
}
