/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentFilePublic } from './documentFilePublic';

export interface DocumentFilespublic {
  data: DocumentFilePublic[];
  count: number | null;
  page: number | null;
  page_size: number | null;
  total_pages: number | null;
}
