/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface DocumentFileBaseCreate {
  /** @maxLength 255 */
  filename: string;
  url_obj: string;
  /** @maxLength 50 */
  type: string;
  size?: string;
}
