/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface DocumentPublic {
  /**
     * @minLength 1
     * @maxLength 255
     */
  title: string;
  category?: string | null;
  original_link?: string | null;
  obj_title?: string | null;
  id: string;
  created_at: string;
}
