/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProfPublic } from './profPublic';

export interface ProfsPublic {
  data: ProfPublic[];
  count: number;
}
