/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ProfPublic {
  name: string;
  university: string | null;
  academic_rank: string | null;
  average_rating?: string | null;
  id: string;
}
