/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ReadMessagesApiV1ChatsIdMessagesGetParams = {
skip?: number;
limit?: number;
};
