/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ReviewCreate {
  /**
     * @minimum 1
     * @maximum 5
     */
  rating?: number;
  content: string | null;
  course_id?: string | null;
  prof_id?: string | null;
}
