/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserPublic } from './userPublic';

export interface UsersPublic {
    data: UserPublic[];
    count: number;
}
