/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface UserRegister {
  /** @maxLength 255 */
  email: string;
  /**
     * @minLength 8
     * @maxLength 128
     */
  password: string;
  full_name?: string | null;
}
