/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ReadReviewsApiV1ReviewsGetParams,
  ReviewCreate,
  ReviewPublic,
  ReviewUpdate,
  ReviewsPublic
} from '../model';

import { customInstance } from '.././axios-custom';
import type { ErrorType , BodyType } from '.././axios-custom';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Read Reviews
 */
export const readReviewsApiV1ReviewsGet = (
    params?: ReadReviewsApiV1ReviewsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ReviewsPublic>(
      {url: `/api/v1/reviews/`, method: 'GET',
        params, signal
    },
      options);
    }




export const getReadReviewsApiV1ReviewsGetInfiniteQueryKey = (params?: ReadReviewsApiV1ReviewsGetParams,) => {
    return [
    'infinite', `/api/v1/reviews/`, ...(params ? [params] : [])
    ] as const;
    }

export const getReadReviewsApiV1ReviewsGetQueryKey = (params?: ReadReviewsApiV1ReviewsGetParams,) => {
    return [
    `/api/v1/reviews/`, ...(params ? [params] : [])
    ] as const;
    }


export const getReadReviewsApiV1ReviewsGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, ReadReviewsApiV1ReviewsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(params?: ReadReviewsApiV1ReviewsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, TError, TData, QueryKey, ReadReviewsApiV1ReviewsGetParams['page']>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadReviewsApiV1ReviewsGetInfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, QueryKey, ReadReviewsApiV1ReviewsGetParams['page']> = ({ signal, pageParam }) => readReviewsApiV1ReviewsGet({...params, 'page': pageParam || params?.['page']}, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, TError, TData, QueryKey, ReadReviewsApiV1ReviewsGetParams['page']> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadReviewsApiV1ReviewsGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>>
export type ReadReviewsApiV1ReviewsGetInfiniteQueryError = ErrorType<HTTPValidationError>


export function useReadReviewsApiV1ReviewsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, ReadReviewsApiV1ReviewsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ReadReviewsApiV1ReviewsGetParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, TError, TData, QueryKey, ReadReviewsApiV1ReviewsGetParams['page']>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>,
          TError,
          Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, QueryKey
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadReviewsApiV1ReviewsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, ReadReviewsApiV1ReviewsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadReviewsApiV1ReviewsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, TError, TData, QueryKey, ReadReviewsApiV1ReviewsGetParams['page']>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>,
          TError,
          Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, QueryKey
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadReviewsApiV1ReviewsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, ReadReviewsApiV1ReviewsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadReviewsApiV1ReviewsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, TError, TData, QueryKey, ReadReviewsApiV1ReviewsGetParams['page']>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Reviews
 */

export function useReadReviewsApiV1ReviewsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, ReadReviewsApiV1ReviewsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadReviewsApiV1ReviewsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, TError, TData, QueryKey, ReadReviewsApiV1ReviewsGetParams['page']>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadReviewsApiV1ReviewsGetInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getReadReviewsApiV1ReviewsGetQueryOptions = <TData = Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, TError = ErrorType<HTTPValidationError>>(params?: ReadReviewsApiV1ReviewsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadReviewsApiV1ReviewsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>> = ({ signal }) => readReviewsApiV1ReviewsGet(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadReviewsApiV1ReviewsGetQueryResult = NonNullable<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>>
export type ReadReviewsApiV1ReviewsGetQueryError = ErrorType<HTTPValidationError>


export function useReadReviewsApiV1ReviewsGet<TData = Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ReadReviewsApiV1ReviewsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>,
          TError,
          Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadReviewsApiV1ReviewsGet<TData = Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadReviewsApiV1ReviewsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>,
          TError,
          Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadReviewsApiV1ReviewsGet<TData = Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadReviewsApiV1ReviewsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Reviews
 */

export function useReadReviewsApiV1ReviewsGet<TData = Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadReviewsApiV1ReviewsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReviewsApiV1ReviewsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadReviewsApiV1ReviewsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Create Review
 */
export const createReviewApiV1ReviewsPost = (
    reviewCreate: BodyType<ReviewCreate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ReviewPublic>(
      {url: `/api/v1/reviews/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reviewCreate, signal
    },
      options);
    }



export const getCreateReviewApiV1ReviewsPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReviewApiV1ReviewsPost>>, TError,{data: BodyType<ReviewCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createReviewApiV1ReviewsPost>>, TError,{data: BodyType<ReviewCreate>}, TContext> => {

const mutationKey = ['createReviewApiV1ReviewsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createReviewApiV1ReviewsPost>>, {data: BodyType<ReviewCreate>}> = (props) => {
          const {data} = props ?? {};

          return  createReviewApiV1ReviewsPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateReviewApiV1ReviewsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createReviewApiV1ReviewsPost>>>
    export type CreateReviewApiV1ReviewsPostMutationBody = BodyType<ReviewCreate>
    export type CreateReviewApiV1ReviewsPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Review
 */
export const useCreateReviewApiV1ReviewsPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReviewApiV1ReviewsPost>>, TError,{data: BodyType<ReviewCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createReviewApiV1ReviewsPost>>,
        TError,
        {data: BodyType<ReviewCreate>},
        TContext
      > => {
      return useMutation(getCreateReviewApiV1ReviewsPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Read Review
 */
export const readReviewApiV1ReviewsIdGet = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ReviewPublic>(
      {url: `/api/v1/reviews/${id}`, method: 'GET', signal
    },
      options);
    }




export const getReadReviewApiV1ReviewsIdGetInfiniteQueryKey = (id: string,) => {
    return [
    'infinite', `/api/v1/reviews/${id}`
    ] as const;
    }

export const getReadReviewApiV1ReviewsIdGetQueryKey = (id: string,) => {
    return [
    `/api/v1/reviews/${id}`
    ] as const;
    }


export const getReadReviewApiV1ReviewsIdGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>>, TError = ErrorType<HTTPValidationError>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadReviewApiV1ReviewsIdGetInfiniteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>> = ({ signal }) => readReviewApiV1ReviewsIdGet(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadReviewApiV1ReviewsIdGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>>
export type ReadReviewApiV1ReviewsIdGetInfiniteQueryError = ErrorType<HTTPValidationError>


export function useReadReviewApiV1ReviewsIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>,
          TError,
          Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadReviewApiV1ReviewsIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>,
          TError,
          Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadReviewApiV1ReviewsIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Review
 */

export function useReadReviewApiV1ReviewsIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadReviewApiV1ReviewsIdGetInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getReadReviewApiV1ReviewsIdGetQueryOptions = <TData = Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>, TError = ErrorType<HTTPValidationError>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadReviewApiV1ReviewsIdGetQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>> = ({ signal }) => readReviewApiV1ReviewsIdGet(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadReviewApiV1ReviewsIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>>
export type ReadReviewApiV1ReviewsIdGetQueryError = ErrorType<HTTPValidationError>


export function useReadReviewApiV1ReviewsIdGet<TData = Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>,
          TError,
          Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadReviewApiV1ReviewsIdGet<TData = Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>,
          TError,
          Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadReviewApiV1ReviewsIdGet<TData = Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Review
 */

export function useReadReviewApiV1ReviewsIdGet<TData = Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReviewApiV1ReviewsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadReviewApiV1ReviewsIdGetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Update Review
 */
export const updateReviewApiV1ReviewsIdPut = (
    id: string,
    reviewUpdate: BodyType<ReviewUpdate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ReviewPublic>(
      {url: `/api/v1/reviews/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: reviewUpdate, signal
    },
      options);
    }



export const getUpdateReviewApiV1ReviewsIdPutMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReviewApiV1ReviewsIdPut>>, TError,{id: string;data: BodyType<ReviewUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateReviewApiV1ReviewsIdPut>>, TError,{id: string;data: BodyType<ReviewUpdate>}, TContext> => {

const mutationKey = ['updateReviewApiV1ReviewsIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateReviewApiV1ReviewsIdPut>>, {id: string;data: BodyType<ReviewUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateReviewApiV1ReviewsIdPut(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateReviewApiV1ReviewsIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateReviewApiV1ReviewsIdPut>>>
    export type UpdateReviewApiV1ReviewsIdPutMutationBody = BodyType<ReviewUpdate>
    export type UpdateReviewApiV1ReviewsIdPutMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Review
 */
export const useUpdateReviewApiV1ReviewsIdPut = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReviewApiV1ReviewsIdPut>>, TError,{id: string;data: BodyType<ReviewUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateReviewApiV1ReviewsIdPut>>,
        TError,
        {id: string;data: BodyType<ReviewUpdate>},
        TContext
      > => {
      return useMutation(getUpdateReviewApiV1ReviewsIdPutMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Review
 */
export const deleteReviewApiV1ReviewsIdDelete = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/api/v1/reviews/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteReviewApiV1ReviewsIdDeleteMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReviewApiV1ReviewsIdDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteReviewApiV1ReviewsIdDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteReviewApiV1ReviewsIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReviewApiV1ReviewsIdDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteReviewApiV1ReviewsIdDelete(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteReviewApiV1ReviewsIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReviewApiV1ReviewsIdDelete>>>

    export type DeleteReviewApiV1ReviewsIdDeleteMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Review
 */
export const useDeleteReviewApiV1ReviewsIdDelete = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReviewApiV1ReviewsIdDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteReviewApiV1ReviewsIdDelete>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteReviewApiV1ReviewsIdDeleteMutationOptions(options), queryClient);
    }
