"""fix_prof_id_uuid_and_timestamp

Revision ID: 1b43b5883fe2
Revises: 968558b4e4d9
Create Date: 2026-05-17 06:46:50.840860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b43b5883fe2'
down_revision: Union[str, Sequence[str], None] = '968558b4e4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_category'), table_name='document')
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_index(op.f('ix_document_title'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url_obj', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('original_link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('document_pkey'))
    )
    op.create_index(op.f('ix_document_title'), 'document', ['title'], unique=False)
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    op.create_index(op.f('ix_document_category'), 'document', ['category'], unique=False)
    # ### end Alembic commands ###
