"""fix_missing_defaults

Revision ID: 69c6a803f607
Revises: a63e1b327f87
Create Date: 2026-05-25 12:30:09.439480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 



# revision identifiers, used by Alembic.
revision: str = '69c6a803f607'
down_revision: Union[str, Sequence[str], None] = 'a63e1b327f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('obj_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'obj_title')
    # ### end Alembic commands ###
