"""fix_missing_defaults

Revision ID: a63e1b327f87
Revises: 78a3391da1ea
Create Date: 2026-05-17 08:33:48.848835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 



# revision identifiers, used by Alembic.
revision: str = 'a63e1b327f87'
down_revision: Union[str, Sequence[str], None] = '78a3391da1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentfile',
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('url_obj', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_obj')
    )
    op.create_index(op.f('ix_documentfile_id'), 'documentfile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentfile_id'), table_name='documentfile')
    op.drop_table('documentfile')
    # ### end Alembic commands ###
