/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ProfCreate,
  ProfPublic,
  ProfUpdate,
  ProfsPublic,
  ReadProfsApiV1ProfsGetParams
} from '../model';

import { customInstance } from '.././axios-custom';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type readProfsApiV1ProfsGetResponse200 = {
  data: ProfsPublic
  status: 200
}

export type readProfsApiV1ProfsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readProfsApiV1ProfsGetResponseSuccess = (readProfsApiV1ProfsGetResponse200) & {
  headers: Headers;
};
export type readProfsApiV1ProfsGetResponseError = (readProfsApiV1ProfsGetResponse422) & {
  headers: Headers;
};

export type readProfsApiV1ProfsGetResponse = (readProfsApiV1ProfsGetResponseSuccess | readProfsApiV1ProfsGetResponseError)

export const getReadProfsApiV1ProfsGetUrl = (params?: ReadProfsApiV1ProfsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/profs/?${stringifiedParams}` : `/api/v1/profs/`
}

/**
 * @summary Read Profs
 */
export const readProfsApiV1ProfsGet = async (params?: ReadProfsApiV1ProfsGetParams, options?: RequestInit): Promise<readProfsApiV1ProfsGetResponse> => {

  return customInstance<readProfsApiV1ProfsGetResponse>(getReadProfsApiV1ProfsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getReadProfsApiV1ProfsGetQueryKey = (params?: ReadProfsApiV1ProfsGetParams,) => {
    return [
    `/api/v1/profs/`, ...(params ? [params] : [])
    ] as const;
    }


export const getReadProfsApiV1ProfsGetQueryOptions = <TData = Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError = HTTPValidationError>(params?: ReadProfsApiV1ProfsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadProfsApiV1ProfsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>> = ({ signal }) => readProfsApiV1ProfsGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadProfsApiV1ProfsGetQueryResult = NonNullable<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>>
export type ReadProfsApiV1ProfsGetQueryError = HTTPValidationError


export function useReadProfsApiV1ProfsGet<TData = Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError = HTTPValidationError>(
 params: undefined |  ReadProfsApiV1ProfsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>,
          TError,
          Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProfsApiV1ProfsGet<TData = Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError = HTTPValidationError>(
 params?: ReadProfsApiV1ProfsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>,
          TError,
          Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProfsApiV1ProfsGet<TData = Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError = HTTPValidationError>(
 params?: ReadProfsApiV1ProfsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Profs
 */

export function useReadProfsApiV1ProfsGet<TData = Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError = HTTPValidationError>(
 params?: ReadProfsApiV1ProfsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadProfsApiV1ProfsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type createProfApiV1ProfsPostResponse200 = {
  data: ProfPublic
  status: 200
}

export type createProfApiV1ProfsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createProfApiV1ProfsPostResponseSuccess = (createProfApiV1ProfsPostResponse200) & {
  headers: Headers;
};
export type createProfApiV1ProfsPostResponseError = (createProfApiV1ProfsPostResponse422) & {
  headers: Headers;
};

export type createProfApiV1ProfsPostResponse = (createProfApiV1ProfsPostResponseSuccess | createProfApiV1ProfsPostResponseError)

export const getCreateProfApiV1ProfsPostUrl = () => {




  return `/api/v1/profs/`
}

/**
 * @summary Create Prof
 */
export const createProfApiV1ProfsPost = async (profCreate: ProfCreate, options?: RequestInit): Promise<createProfApiV1ProfsPostResponse> => {

  return customInstance<createProfApiV1ProfsPostResponse>(getCreateProfApiV1ProfsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(profCreate)
  }
);}




export const getCreateProfApiV1ProfsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProfApiV1ProfsPost>>, TError,{data: ProfCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createProfApiV1ProfsPost>>, TError,{data: ProfCreate}, TContext> => {

const mutationKey = ['createProfApiV1ProfsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProfApiV1ProfsPost>>, {data: ProfCreate}> = (props) => {
          const {data} = props ?? {};

          return  createProfApiV1ProfsPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateProfApiV1ProfsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createProfApiV1ProfsPost>>>
    export type CreateProfApiV1ProfsPostMutationBody = ProfCreate
    export type CreateProfApiV1ProfsPostMutationError = HTTPValidationError

    /**
 * @summary Create Prof
 */
export const useCreateProfApiV1ProfsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProfApiV1ProfsPost>>, TError,{data: ProfCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProfApiV1ProfsPost>>,
        TError,
        {data: ProfCreate},
        TContext
      > => {
      return useMutation(getCreateProfApiV1ProfsPostMutationOptions(options), queryClient);
    }
    export type readProfApiV1ProfsIdGetResponse200 = {
  data: ProfPublic
  status: 200
}

export type readProfApiV1ProfsIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readProfApiV1ProfsIdGetResponseSuccess = (readProfApiV1ProfsIdGetResponse200) & {
  headers: Headers;
};
export type readProfApiV1ProfsIdGetResponseError = (readProfApiV1ProfsIdGetResponse422) & {
  headers: Headers;
};

export type readProfApiV1ProfsIdGetResponse = (readProfApiV1ProfsIdGetResponseSuccess | readProfApiV1ProfsIdGetResponseError)

export const getReadProfApiV1ProfsIdGetUrl = (id: string,) => {




  return `/api/v1/profs/${id}`
}

/**
 * @summary Read Prof
 */
export const readProfApiV1ProfsIdGet = async (id: string, options?: RequestInit): Promise<readProfApiV1ProfsIdGetResponse> => {

  return customInstance<readProfApiV1ProfsIdGetResponse>(getReadProfApiV1ProfsIdGetUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getReadProfApiV1ProfsIdGetQueryKey = (id: string,) => {
    return [
    `/api/v1/profs/${id}`
    ] as const;
    }


export const getReadProfApiV1ProfsIdGetQueryOptions = <TData = Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError = HTTPValidationError>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadProfApiV1ProfsIdGetQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>> = ({ signal }) => readProfApiV1ProfsIdGet(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadProfApiV1ProfsIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>>
export type ReadProfApiV1ProfsIdGetQueryError = HTTPValidationError


export function useReadProfApiV1ProfsIdGet<TData = Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError = HTTPValidationError>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>,
          TError,
          Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProfApiV1ProfsIdGet<TData = Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>,
          TError,
          Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProfApiV1ProfsIdGet<TData = Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Prof
 */

export function useReadProfApiV1ProfsIdGet<TData = Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadProfApiV1ProfsIdGetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type updateProfApiV1ProfsIdPutResponse200 = {
  data: ProfPublic
  status: 200
}

export type updateProfApiV1ProfsIdPutResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateProfApiV1ProfsIdPutResponseSuccess = (updateProfApiV1ProfsIdPutResponse200) & {
  headers: Headers;
};
export type updateProfApiV1ProfsIdPutResponseError = (updateProfApiV1ProfsIdPutResponse422) & {
  headers: Headers;
};

export type updateProfApiV1ProfsIdPutResponse = (updateProfApiV1ProfsIdPutResponseSuccess | updateProfApiV1ProfsIdPutResponseError)

export const getUpdateProfApiV1ProfsIdPutUrl = (id: string,) => {




  return `/api/v1/profs/${id}`
}

/**
 * @summary Update Prof
 */
export const updateProfApiV1ProfsIdPut = async (id: string,
    profUpdate: ProfUpdate, options?: RequestInit): Promise<updateProfApiV1ProfsIdPutResponse> => {

  return customInstance<updateProfApiV1ProfsIdPutResponse>(getUpdateProfApiV1ProfsIdPutUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(profUpdate)
  }
);}




export const getUpdateProfApiV1ProfsIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProfApiV1ProfsIdPut>>, TError,{id: string;data: ProfUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProfApiV1ProfsIdPut>>, TError,{id: string;data: ProfUpdate}, TContext> => {

const mutationKey = ['updateProfApiV1ProfsIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProfApiV1ProfsIdPut>>, {id: string;data: ProfUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  updateProfApiV1ProfsIdPut(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateProfApiV1ProfsIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateProfApiV1ProfsIdPut>>>
    export type UpdateProfApiV1ProfsIdPutMutationBody = ProfUpdate
    export type UpdateProfApiV1ProfsIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Prof
 */
export const useUpdateProfApiV1ProfsIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProfApiV1ProfsIdPut>>, TError,{id: string;data: ProfUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProfApiV1ProfsIdPut>>,
        TError,
        {id: string;data: ProfUpdate},
        TContext
      > => {
      return useMutation(getUpdateProfApiV1ProfsIdPutMutationOptions(options), queryClient);
    }
    export type deleteProfApiV1ProfsIdDeleteResponse200 = {
  data: unknown
  status: 200
}

export type deleteProfApiV1ProfsIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteProfApiV1ProfsIdDeleteResponseSuccess = (deleteProfApiV1ProfsIdDeleteResponse200) & {
  headers: Headers;
};
export type deleteProfApiV1ProfsIdDeleteResponseError = (deleteProfApiV1ProfsIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteProfApiV1ProfsIdDeleteResponse = (deleteProfApiV1ProfsIdDeleteResponseSuccess | deleteProfApiV1ProfsIdDeleteResponseError)

export const getDeleteProfApiV1ProfsIdDeleteUrl = (id: string,) => {




  return `/api/v1/profs/${id}`
}

/**
 * @summary Delete Prof
 */
export const deleteProfApiV1ProfsIdDelete = async (id: string, options?: RequestInit): Promise<deleteProfApiV1ProfsIdDeleteResponse> => {

  return customInstance<deleteProfApiV1ProfsIdDeleteResponse>(getDeleteProfApiV1ProfsIdDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteProfApiV1ProfsIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProfApiV1ProfsIdDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProfApiV1ProfsIdDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteProfApiV1ProfsIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProfApiV1ProfsIdDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteProfApiV1ProfsIdDelete(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteProfApiV1ProfsIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProfApiV1ProfsIdDelete>>>

    export type DeleteProfApiV1ProfsIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Prof
 */
export const useDeleteProfApiV1ProfsIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProfApiV1ProfsIdDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProfApiV1ProfsIdDelete>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteProfApiV1ProfsIdDeleteMutationOptions(options), queryClient);
    }
