/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ProfCreate,
  ProfPublic,
  ProfUpdate,
  ProfsPublic,
  ReadProfsApiV1ProfsGetParams
} from '../model';

import { customInstance } from '.././axios-custom';
import type { ErrorType , BodyType } from '.././axios-custom';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Read Profs
 */
export const readProfsApiV1ProfsGet = (
    params?: ReadProfsApiV1ProfsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ProfsPublic>(
      {url: `/api/v1/profs/`, method: 'GET',
        params, signal
    },
      options);
    }




export const getReadProfsApiV1ProfsGetInfiniteQueryKey = (params?: ReadProfsApiV1ProfsGetParams,) => {
    return [
    'infinite', `/api/v1/profs/`, ...(params ? [params] : [])
    ] as const;
    }

export const getReadProfsApiV1ProfsGetQueryKey = (params?: ReadProfsApiV1ProfsGetParams,) => {
    return [
    `/api/v1/profs/`, ...(params ? [params] : [])
    ] as const;
    }


export const getReadProfsApiV1ProfsGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, ReadProfsApiV1ProfsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(params?: ReadProfsApiV1ProfsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData, QueryKey, ReadProfsApiV1ProfsGetParams['page']>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadProfsApiV1ProfsGetInfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, QueryKey, ReadProfsApiV1ProfsGetParams['page']> = ({ signal, pageParam }) => readProfsApiV1ProfsGet({...params, 'page': pageParam || params?.['page']}, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData, QueryKey, ReadProfsApiV1ProfsGetParams['page']> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadProfsApiV1ProfsGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>>
export type ReadProfsApiV1ProfsGetInfiniteQueryError = ErrorType<HTTPValidationError>


export function useReadProfsApiV1ProfsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, ReadProfsApiV1ProfsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ReadProfsApiV1ProfsGetParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData, QueryKey, ReadProfsApiV1ProfsGetParams['page']>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>,
          TError,
          Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, QueryKey
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProfsApiV1ProfsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, ReadProfsApiV1ProfsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadProfsApiV1ProfsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData, QueryKey, ReadProfsApiV1ProfsGetParams['page']>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>,
          TError,
          Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, QueryKey
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProfsApiV1ProfsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, ReadProfsApiV1ProfsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadProfsApiV1ProfsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData, QueryKey, ReadProfsApiV1ProfsGetParams['page']>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Profs
 */

export function useReadProfsApiV1ProfsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, ReadProfsApiV1ProfsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadProfsApiV1ProfsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData, QueryKey, ReadProfsApiV1ProfsGetParams['page']>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadProfsApiV1ProfsGetInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getReadProfsApiV1ProfsGetQueryOptions = <TData = Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError = ErrorType<HTTPValidationError>>(params?: ReadProfsApiV1ProfsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadProfsApiV1ProfsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>> = ({ signal }) => readProfsApiV1ProfsGet(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadProfsApiV1ProfsGetQueryResult = NonNullable<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>>
export type ReadProfsApiV1ProfsGetQueryError = ErrorType<HTTPValidationError>


export function useReadProfsApiV1ProfsGet<TData = Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ReadProfsApiV1ProfsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>,
          TError,
          Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProfsApiV1ProfsGet<TData = Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadProfsApiV1ProfsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>,
          TError,
          Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProfsApiV1ProfsGet<TData = Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadProfsApiV1ProfsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Profs
 */

export function useReadProfsApiV1ProfsGet<TData = Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ReadProfsApiV1ProfsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfsApiV1ProfsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadProfsApiV1ProfsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Create Prof
 */
export const createProfApiV1ProfsPost = (
    profCreate: BodyType<ProfCreate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ProfPublic>(
      {url: `/api/v1/profs/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: profCreate, signal
    },
      options);
    }



export const getCreateProfApiV1ProfsPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProfApiV1ProfsPost>>, TError,{data: BodyType<ProfCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createProfApiV1ProfsPost>>, TError,{data: BodyType<ProfCreate>}, TContext> => {

const mutationKey = ['createProfApiV1ProfsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProfApiV1ProfsPost>>, {data: BodyType<ProfCreate>}> = (props) => {
          const {data} = props ?? {};

          return  createProfApiV1ProfsPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateProfApiV1ProfsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createProfApiV1ProfsPost>>>
    export type CreateProfApiV1ProfsPostMutationBody = BodyType<ProfCreate>
    export type CreateProfApiV1ProfsPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Prof
 */
export const useCreateProfApiV1ProfsPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProfApiV1ProfsPost>>, TError,{data: BodyType<ProfCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProfApiV1ProfsPost>>,
        TError,
        {data: BodyType<ProfCreate>},
        TContext
      > => {
      return useMutation(getCreateProfApiV1ProfsPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Read Prof
 */
export const readProfApiV1ProfsIdGet = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ProfPublic>(
      {url: `/api/v1/profs/${id}`, method: 'GET', signal
    },
      options);
    }




export const getReadProfApiV1ProfsIdGetInfiniteQueryKey = (id: string,) => {
    return [
    'infinite', `/api/v1/profs/${id}`
    ] as const;
    }

export const getReadProfApiV1ProfsIdGetQueryKey = (id: string,) => {
    return [
    `/api/v1/profs/${id}`
    ] as const;
    }


export const getReadProfApiV1ProfsIdGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>>, TError = ErrorType<HTTPValidationError>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadProfApiV1ProfsIdGetInfiniteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>> = ({ signal }) => readProfApiV1ProfsIdGet(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadProfApiV1ProfsIdGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>>
export type ReadProfApiV1ProfsIdGetInfiniteQueryError = ErrorType<HTTPValidationError>


export function useReadProfApiV1ProfsIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>,
          TError,
          Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProfApiV1ProfsIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>,
          TError,
          Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProfApiV1ProfsIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Prof
 */

export function useReadProfApiV1ProfsIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadProfApiV1ProfsIdGetInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getReadProfApiV1ProfsIdGetQueryOptions = <TData = Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError = ErrorType<HTTPValidationError>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadProfApiV1ProfsIdGetQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>> = ({ signal }) => readProfApiV1ProfsIdGet(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadProfApiV1ProfsIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>>
export type ReadProfApiV1ProfsIdGetQueryError = ErrorType<HTTPValidationError>


export function useReadProfApiV1ProfsIdGet<TData = Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>,
          TError,
          Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProfApiV1ProfsIdGet<TData = Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>,
          TError,
          Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProfApiV1ProfsIdGet<TData = Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Prof
 */

export function useReadProfApiV1ProfsIdGet<TData = Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError = ErrorType<HTTPValidationError>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProfApiV1ProfsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadProfApiV1ProfsIdGetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Update Prof
 */
export const updateProfApiV1ProfsIdPut = (
    id: string,
    profUpdate: BodyType<ProfUpdate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ProfPublic>(
      {url: `/api/v1/profs/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: profUpdate, signal
    },
      options);
    }



export const getUpdateProfApiV1ProfsIdPutMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProfApiV1ProfsIdPut>>, TError,{id: string;data: BodyType<ProfUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProfApiV1ProfsIdPut>>, TError,{id: string;data: BodyType<ProfUpdate>}, TContext> => {

const mutationKey = ['updateProfApiV1ProfsIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProfApiV1ProfsIdPut>>, {id: string;data: BodyType<ProfUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateProfApiV1ProfsIdPut(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateProfApiV1ProfsIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateProfApiV1ProfsIdPut>>>
    export type UpdateProfApiV1ProfsIdPutMutationBody = BodyType<ProfUpdate>
    export type UpdateProfApiV1ProfsIdPutMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Prof
 */
export const useUpdateProfApiV1ProfsIdPut = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProfApiV1ProfsIdPut>>, TError,{id: string;data: BodyType<ProfUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProfApiV1ProfsIdPut>>,
        TError,
        {id: string;data: BodyType<ProfUpdate>},
        TContext
      > => {
      return useMutation(getUpdateProfApiV1ProfsIdPutMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Prof
 */
export const deleteProfApiV1ProfsIdDelete = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<unknown>(
      {url: `/api/v1/profs/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteProfApiV1ProfsIdDeleteMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProfApiV1ProfsIdDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProfApiV1ProfsIdDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteProfApiV1ProfsIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProfApiV1ProfsIdDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteProfApiV1ProfsIdDelete(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteProfApiV1ProfsIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProfApiV1ProfsIdDelete>>>

    export type DeleteProfApiV1ProfsIdDeleteMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Prof
 */
export const useDeleteProfApiV1ProfsIdDelete = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProfApiV1ProfsIdDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProfApiV1ProfsIdDelete>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteProfApiV1ProfsIdDeleteMutationOptions(options), queryClient);
    }
