/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  BodyLoginAccessTokenApiV1LoginAccessTokenPost,
  HTTPValidationError,
  Token,
  UserPublic,
  UserRegister
} from '../model';

import { customInstance } from '.././axios-custom';
import type { ErrorType , BodyType } from '.././axios-custom';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * OAuth2 compatible token login, get an access token for future requests
 * @summary Login Access Token
 */
export const loginAccessTokenApiV1LoginAccessTokenPost = (
    bodyLoginAccessTokenApiV1LoginAccessTokenPost: BodyType<BodyLoginAccessTokenApiV1LoginAccessTokenPost>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {

      const formUrlEncoded = new URLSearchParams();
if(bodyLoginAccessTokenApiV1LoginAccessTokenPost.grant_type !== undefined && bodyLoginAccessTokenApiV1LoginAccessTokenPost.grant_type !== null) {
 formUrlEncoded.append(`grant_type`, bodyLoginAccessTokenApiV1LoginAccessTokenPost.grant_type);
 }
formUrlEncoded.append(`username`, bodyLoginAccessTokenApiV1LoginAccessTokenPost.username);
formUrlEncoded.append(`password`, bodyLoginAccessTokenApiV1LoginAccessTokenPost.password);
if(bodyLoginAccessTokenApiV1LoginAccessTokenPost.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyLoginAccessTokenApiV1LoginAccessTokenPost.scope);
 }
if(bodyLoginAccessTokenApiV1LoginAccessTokenPost.client_id !== undefined && bodyLoginAccessTokenApiV1LoginAccessTokenPost.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyLoginAccessTokenApiV1LoginAccessTokenPost.client_id);
 }
if(bodyLoginAccessTokenApiV1LoginAccessTokenPost.client_secret !== undefined && bodyLoginAccessTokenApiV1LoginAccessTokenPost.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyLoginAccessTokenApiV1LoginAccessTokenPost.client_secret);
 }

      return customInstance<Token>(
      {url: `/api/v1/login/access-token`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded, signal
    },
      options);
    }



export const getLoginAccessTokenApiV1LoginAccessTokenPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAccessTokenApiV1LoginAccessTokenPost>>, TError,{data: BodyType<BodyLoginAccessTokenApiV1LoginAccessTokenPost>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof loginAccessTokenApiV1LoginAccessTokenPost>>, TError,{data: BodyType<BodyLoginAccessTokenApiV1LoginAccessTokenPost>}, TContext> => {

const mutationKey = ['loginAccessTokenApiV1LoginAccessTokenPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginAccessTokenApiV1LoginAccessTokenPost>>, {data: BodyType<BodyLoginAccessTokenApiV1LoginAccessTokenPost>}> = (props) => {
          const {data} = props ?? {};

          return  loginAccessTokenApiV1LoginAccessTokenPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginAccessTokenApiV1LoginAccessTokenPostMutationResult = NonNullable<Awaited<ReturnType<typeof loginAccessTokenApiV1LoginAccessTokenPost>>>
    export type LoginAccessTokenApiV1LoginAccessTokenPostMutationBody = BodyType<BodyLoginAccessTokenApiV1LoginAccessTokenPost>
    export type LoginAccessTokenApiV1LoginAccessTokenPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Login Access Token
 */
export const useLoginAccessTokenApiV1LoginAccessTokenPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAccessTokenApiV1LoginAccessTokenPost>>, TError,{data: BodyType<BodyLoginAccessTokenApiV1LoginAccessTokenPost>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginAccessTokenApiV1LoginAccessTokenPost>>,
        TError,
        {data: BodyType<BodyLoginAccessTokenApiV1LoginAccessTokenPost>},
        TContext
      > => {
      return useMutation(getLoginAccessTokenApiV1LoginAccessTokenPostMutationOptions(options), queryClient);
    }
    /**
 * Create new user without the need to be logged in.
 * @summary Register User
 */
export const registerUserApiV1SignupPost = (
    userRegister: BodyType<UserRegister>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UserPublic>(
      {url: `/api/v1/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userRegister, signal
    },
      options);
    }



export const getRegisterUserApiV1SignupPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUserApiV1SignupPost>>, TError,{data: BodyType<UserRegister>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof registerUserApiV1SignupPost>>, TError,{data: BodyType<UserRegister>}, TContext> => {

const mutationKey = ['registerUserApiV1SignupPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerUserApiV1SignupPost>>, {data: BodyType<UserRegister>}> = (props) => {
          const {data} = props ?? {};

          return  registerUserApiV1SignupPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterUserApiV1SignupPostMutationResult = NonNullable<Awaited<ReturnType<typeof registerUserApiV1SignupPost>>>
    export type RegisterUserApiV1SignupPostMutationBody = BodyType<UserRegister>
    export type RegisterUserApiV1SignupPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Register User
 */
export const useRegisterUserApiV1SignupPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUserApiV1SignupPost>>, TError,{data: BodyType<UserRegister>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerUserApiV1SignupPost>>,
        TError,
        {data: BodyType<UserRegister>},
        TContext
      > => {
      return useMutation(getRegisterUserApiV1SignupPostMutationOptions(options), queryClient);
    }
