/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  UserPublic
} from '../model';

import { customInstance } from '.././axios-custom';
import type { ErrorType } from '.././axios-custom';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Current User
 */
export const getCurrentUserApiV1UserMeGet = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UserPublic>(
      {url: `/api/v1/user/me`, method: 'GET', signal
    },
      options);
    }




export const getGetCurrentUserApiV1UserMeGetInfiniteQueryKey = () => {
    return [
    'infinite', `/api/v1/user/me`
    ] as const;
    }

export const getGetCurrentUserApiV1UserMeGetQueryKey = () => {
    return [
    `/api/v1/user/me`
    ] as const;
    }


export const getGetCurrentUserApiV1UserMeGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentUserApiV1UserMeGetInfiniteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>> = ({ signal }) => getCurrentUserApiV1UserMeGet(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentUserApiV1UserMeGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>>
export type GetCurrentUserApiV1UserMeGetInfiniteQueryError = ErrorType<unknown>


export function useGetCurrentUserApiV1UserMeGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUserApiV1UserMeGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUserApiV1UserMeGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Current User
 */

export function useGetCurrentUserApiV1UserMeGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCurrentUserApiV1UserMeGetInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetCurrentUserApiV1UserMeGetQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentUserApiV1UserMeGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>> = ({ signal }) => getCurrentUserApiV1UserMeGet(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentUserApiV1UserMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>>
export type GetCurrentUserApiV1UserMeGetQueryError = ErrorType<unknown>


export function useGetCurrentUserApiV1UserMeGet<TData = Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUserApiV1UserMeGet<TData = Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUserApiV1UserMeGet<TData = Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Current User
 */

export function useGetCurrentUserApiV1UserMeGet<TData = Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserApiV1UserMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCurrentUserApiV1UserMeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






